name: Build
 
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet packages
      run: nuget restore WinWeelay.sln
 
    - name: Build project
      run: msbuild WinWeelay.sln /p:Configuration=Release
        
    - name: Create installer
      uses: joncloud/makensis-action@v3.4
      with: 
        script-file: setup.nsi

    - name: Upload build file
      uses: actions/upload-artifact@v1.0.0
      with:
        name: files
        path: Release
          
    - name: Upload installer
      uses: actions/upload-artifact@v1.0.0
      with:
        name: installer
        path: Release\WinWeelaySetup.exe
