name: Build
 
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
        
    - name: Create Installer
      uses: joncloud/makensis-action@v4
      with: 
        script-file: setup.nsi

    - name: Upload Build Files
      uses: actions/upload-artifact@v4.4.3
      with:
        name: files
        path: Release
